apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    f5nr: "true"
  name: extended-spec-config
  namespace: kube-system
data:
  extendedSpec: |
    externalClustersConfig:
    - clusterName: cluster3
      secret: default/external-cluster
    extendedRouteSpec:
    - allowOverride: false
      namespace: cafeone
      vserverAddr: 10.8.0.4
      vserverName: vs-coffee